config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :update, :destroy, :edit] do
    resources :reactions, only: [:create]
  end
  resources :meetings, except: [:index] do
    post :start
  end
  resources :members do
    get :accept_membership
  end
  resource :team, except: [:index] do
    post :request_invite
  end
  devise_for :users

  resources :users, except: [:new, :create] do
    get :current
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#current"
end

app/models/meeting.rb
class Meeting < ApplicationRecord
  has_many :comments

  def not_started?
    started_at.nil?
  end
  def started?
    !not_started?
  end
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  before_action :set_meeting, only: %i[ show edit update destroy start ]

  # GET /meetings/1
  def show
    @hits = Comments::Hit.where(meeting: @meeting)
    @misses = Comments::Miss.where(meeting: @meeting)
  end

  # GET /meetings/new
  def new
    @meeting = Meeting.new(date: Date.today)
  end

  # GET /meetings/1/edit
  def edit
  end

  # POST /meetings
  def create
    @meeting = Meeting.new(meeting_params)

    if @meeting.save
      redirect_to team_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def start
    duration = params.require(:meeting)[:duration]
    @meeting.update(started_at: Time.now, duration_seconds: duration.to_i * 60)
    Turbo::StreamsChannel.broadcast_stream_to(dom_id(@meeting) + Apartment::Tenant.current, content: render(template: "meetings/start_meeting", format: :turbo_stream))
  end

  # PATCH/PUT /meetings/1
  def update
    if @meeting.update(meeting_params)
      redirect_to @meeting, notice: "Meeting was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /meetings/1
  def destroy
    @meeting.destroy
    redirect_to meetings_url, notice: "Meeting was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting
      @meeting = Meeting.find(params[:id] || params[:meeting_id] )
    end

    # Only allow a list of trusted parameters through.
    def meeting_params
      params.require(:meeting).permit(:date, :name)
    end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_with(model: meeting) do |form| %>
  <% if meeting.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
        <% meeting.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.hidden_field :date %>
  </div>

  <div class="flex flex-col items-center space-y-3">
    <%= form.text_field :name,
      class:"form-control block w-full px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
      placeholder:"new meeting name" %>

    <div>
      <%= form.submit "Create hit and miss! 💩", class: "inline-block px-7 py-3 bg-gradient-to-r from-orange-300 via-orange-500 to-red-600 text-white font-medium text-sm leading-snug rounded shadow-md hover:from-orange-200 hover:via-orange-400 hover:to-red-500 hover:shadow-lg active:bg-orange-500 active:shadow-lg transition duration-150 ease-in-out w-full" %>
    </div>
  </div>
<% end %>

app/views/meetings/_hits_and_misses.html.erb
<div class="flex space-x-2">
  <div class="flex flex-col w-1/2">
    <h2 class="text-xl mb-5 font-medium text-slate-900">Hit</h2>

    <div class="bg-white rounded-lg drop-shadow p-3 mb-3">
      <%= form_with model: Comments::Hit.new, url: comments_path do |form| %>
        <div class="flex flex-col items-center space-y-3">
          <%= form.hidden_field :meeting_id, value: @meeting.id %>
          <%= form.hidden_field :type, value: "Comments::Hit" %>
          <div class="field w-full">
            <%= form.rich_text_area :body %>
          </div>
          <%= form.submit "Hit 🥳", class: "text-xl inline-block px-3 py-3 bg-gradient-to-r from-emerald-300 via-emerald-500 to-cyan-600 text-white font-medium text-sm leading-snug rounded shadow-md hover:from-emerald-200 hover:via-emerald-400 hover:to-cyan-500 hover:shadow-lg active:from-emerald-100 active:via-emerald-300 active:to-cyan-400 active:shadow-lg transition duration-150 ease-in-out w-32 text-center" %>
        </div>
      <% end %>
    </div>
    <div role="list">
      <%= turbo_frame_tag :hit_list, class:"divide-y divide-gray-200" do %>
        <%= render hits %>
      <% end %>
    </div>
  </div>
  <div class="flex flex-col w-1/2">
    <h2 class="text-xl mb-5 font-medium text-slate-900">Miss</h2>
    <div class="bg-white rounded-lg drop-shadow p-3 mb-3">
      <%= form_with model: Comments::Miss.new, url: comments_path do |form| %>
        <div class="flex flex-col items-center space-y-3">
          <%= form.hidden_field :meeting_id, value: @meeting.id %>
          <%= form.hidden_field :type, value: "Comments::Miss" %>
          <div class="field w-full">
            <%= form.rich_text_area :body %>
          </div>
          <%= form.submit "Miss 💩", class: "text-xl inline-block px-3 py-3 bg-gradient-to-r from-orange-300 via-orange-500 to-red-600 text-white font-medium text-sm leading-snug rounded shadow-md hover:from-orange-200 hover:via-orange-400 hover:to-red-500 hover:shadow-lg active:from-orange-100 active:via-orange-300 active:to-red-400 active:shadow-lg transition duration-150 ease-in-out w-32 text-center" %>
        </div>
      <% end %>
    </div>
    <div role="list">
      <%= turbo_frame_tag :miss_list, class:"flex flex-col space-y-2" do %>
        <%= render misses %>
      <% end %>
    </div>
  </div>
</div>

app/views/meetings/_meeting.html.erb
<li>
  <%= link_to meeting_path(meeting) do %>
    <div class="p-4 flex justify-between">
      <div class="mx-3">
        <p class="text-sm  font-medium text-blue-700">
          <%= meeting.name %>
        </p>
        <p class="text-sm text-gray-500"><%= l(meeting.date, format: :long) %></p>
      </div>
      <div>
        <% if meeting.started_at? && (meeting.started_at + meeting.duration_seconds&.seconds) < Time.now %>
          <div class="bg-orange-400 rounded text-white font-semibold p-1">
            ended
          </div>
        <% end %>
      </div>
    </div>
  <% end %>
</li>

app/views/meetings/_start_meeting_form.html.erb
<%= form_with model: meeting, url: meeting_start_path(meeting), method: :post do |form| %>
  <div class="flex flex-col items-center space-y-3">
    <%= form.number_field :duration,
      class:"form-control block w-96 px-4 py-2 text-xl font-normal text-gray-700 bg-white bg-clip-padding border border-solid border-gray-300 rounded transition ease-in-out m-0 focus:text-gray-700 focus:bg-white focus:border-blue-600 focus:outline-none",
      placeholder:"duration (minutes)" %>

    <div>
      <%= form.submit "Start", class: "inline-block px-7 py-3 bg-gradient-to-r from-orange-300 via-orange-500 to-red-600 text-white font-medium text-sm leading-snug rounded shadow-md hover:from-orange-200 hover:via-orange-400 hover:to-red-500 hover:shadow-lg active:bg-orange-500 active:shadow-lg transition duration-150 ease-in-out w-full" %>
    </div>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render "form", meeting: @meeting %>

<br>

<div>
  <%= link_to "Show this meeting", @meeting %> |
  <%= link_to "Back to meetings", meetings_path %>
</div>

app/views/meetings/index.html.erb
<%= turbo_frame_tag :meetings, target: "_top" do %>
  <h1>Meetings</h1>

  <%= turbo_frame_tag :new_meeting, src: new_meeting_path %>

  <div id="meetings">
    <% @meetings.each do |meeting| %>
      <%= render meeting %>
    <% end %>
  </div>

<% end %>

app/views/meetings/new.html.erb
<%= turbo_frame_tag :new_meeting do %>
  <div class="bg-white rounded-lg drop-shadow mb-2 p-4">
    <%= render "form", meeting: @meeting %>
  </div>
<% end %>

app/views/meetings/show.html.erb
<%= turbo_stream_from dom_id(@meeting) + Apartment::Tenant.current %>
<%= turbo_frame_tag @meeting do %>
  <div class="max-w-7xl mx-auto py-6 sm:px-6 lg:px-8">
    <h1 class="text-4xl mb-5 font-bold text-slate-400"><%= @meeting.name %> </h1>

    <% if @meeting.not_started? %>
      <div class="mt-32">
        <% if can?(:start, @meeting) %>
          <%= render partial: "start_meeting_form", locals: { meeting: @meeting } %>
        <% else %>
          Wainting for host to start the meeting...
        <% end %>
      </div>
    <% else %>
      <%= tag.div class: "font-mono text-3xl font-semibold",
      data: {
        controller: "timer",
        timer_end_at_value: (@meeting.started_at + @meeting.duration_seconds.seconds).iso8601,
      } do %>
        --:--
      <% end %>
      <%= render partial: "meetings/hits_and_misses", locals: { meeting: @meeting, hits: @hits, misses: @misses } %>
    <% end %>
  </div>
<% end %>

app/views/meetings/start_meeting.turbo_stream.erb
<%= turbo_stream.update(@meeting) do %>
  <%= render template: "meetings/show" %>
<% end %>