config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :update, :destroy, :edit] do
    resources :reactions, only: [:create]
  end
  resources :meetings, except: [:index] do
    post :start
  end
  resources :members do
    get :accept_membership
  end
  resource :team, except: [:index] do
    post :request_invite
  end
  devise_for :users

  resources :users, except: [:new, :create] do
    get :current
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#current"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :author, class_name: "Member"
  belongs_to :meeting

  has_many :reactions, dependent: :destroy

  has_rich_text :body

  validates :body, presence: true
end

app/models/comments/hit.rb
class Comments::Hit < Comment
end

app/models/comments/miss.rb
class Comments::Miss < Comment
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[ show edit update destroy ]

  # GET /comments/new
  def new
    @comment = Comment.new
  end

  # GET /comments/1/edit
  def edit
  end

  # POST /comments
  def create
    @comment = Comment.new(comment_params.merge(author: current_member))
    if @comment.save
      Turbo::StreamsChannel.broadcast_stream_to(dom_id(@comment.meeting) + Apartment::Tenant.current, content: render_to_string(template: "comments/create", format: :turbo_stream))
      if @comment.body.to_plain_text == "never gonna give you up"
        Turbo::StreamsChannel.broadcast_stream_to(dom_id(@comment.meeting) + Apartment::Tenant.current, content: render_to_string(template: "comments/rick_roll", format: :turbo_stream))
      end
    end
    head 200
  end

  # PATCH/PUT /comments/1
  def update
    if @comment.update(comment_params)
      redirect_to @comment, notice: "Comment was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /comments/1
  def destroy
    @comment.destroy
    redirect_to comments_url, notice: "Comment was successfully destroyed."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_comment
    @comment = Comment.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def comment_params
    if params[:comments_miss]
      params.require(:comments_miss).permit(:type, :meeting_id, :body)
    else
      params.require(:comments_hit).permit(:type, :meeting_id, :body)
    end
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.erb
<div id="<%= dom_id comment %>" class="p-2 bg-white rounded-lg border-2">
  <div class="text-sm text-slate-400">
    <%= comment.author.user.username %> said:
  </div>

  <div class="border-b-2">
    <p class="prose">
      <%= comment.body %>
    </p>
  </div>
  <div class="flex justify-between pt-1">
    <%= turbo_frame_tag dom_id(comment) + "_reactions", class: "flex" do %>
      <%= render comment.reactions %>
    <% end %>

    <%= render partial: "reactions/reaction_form", locals: {comment: comment}%>
  </div>
</div>

app/views/comments/_form.html.erb
<%= form_with(model: comment) do |form| %>
  <% if comment.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :type, style: "display: block" %>
    <%= form.text_field :type %>
  </div>

  <div>
    <%= form.label :author_id, style: "display: block" %>
    <%= form.text_field :author_id %>
  </div>

  <div>
    <%= form.label :meeting_id, style: "display: block" %>
    <%= form.text_field :meeting_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/comments/create.turbo_stream.erb
<% target_frame = @comment.is_a?(Comments::Hit) ? "hit_list" : "miss_list" %>
<%= turbo_stream.append(target_frame) do %>
  <%= render @comment %>
<% end %>

app/views/comments/edit.html.erb
<h1>Editing comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Show this comment", @comment %> |
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/index.html.erb
<h1>Comments</h1>

<div id="comments">
  <% @comments.each do |comment| %>
    <%= render comment %>
    <p>
      <%= link_to "Show this comment", comment %>
    </p>
  <% end %>
</div>

<%= link_to "New comment", new_comment_path %>

app/views/comments/new.html.erb
<h1>New comment</h1>

<%= render "form", comment: @comment %>

<br>

<div>
  <%= link_to "Back to comments", comments_path %>
</div>

app/views/comments/rick_roll.turbo_stream.erb
<% target_frame = @comment.is_a?(Comments::Hit) ? "hit_list" : "miss_list" %>
<%= turbo_stream.append(target_frame) do %>
  <iframe width="420" height="345" src="https://www.youtube.com/embed/dQw4w9WgXcQ?autoplay=1" autoplay frameborder="0" allowfullscreen></iframe>
<% end %>

app/views/comments/show.html.erb
<%= render @comment %>

<div>
  <%= link_to "Edit this comment", edit_comment_path(@comment) %> |
  <%= link_to "Back to comments", comments_path %>

  <%= button_to "Destroy this comment", @comment, method: :delete %>
</div>