config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :update, :destroy, :edit] do
    resources :reactions, only: [:create]
  end
  resources :meetings, except: [:index] do
    post :start
  end
  resources :members do
    get :accept_membership
  end
  resource :team, except: [:index] do
    post :request_invite
  end
  devise_for :users

  resources :users, except: [:new, :create] do
    get :current
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#current"
end

app/controllers/reactions_controller.rb
class ReactionsController < ApplicationController
  before_action :set_reaction, only: %i[ show edit update destroy ]

  # GET /reactions
  def index
    @reactions = Reaction.all
  end

  # GET /reactions/1
  def show
  end

  # GET /reactions/new
  def new
    @reaction = Reaction.new
  end

  # GET /reactions/1/edit
  def edit
  end

  # POST /reactions
  def create
    @reaction = Reaction.new(reaction_params.merge(author: current_member, comment_id: params[:comment_id]))

    @reaction.save
    Turbo::StreamsChannel.broadcast_stream_to(dom_id(@reaction.comment.meeting) + Apartment::Tenant.current, content: render(template: "reactions/create", format: :turbo_stream))
  end

  # PATCH/PUT /reactions/1
  def update
    if @reaction.update(reaction_params)
      redirect_to @reaction, notice: "Reaction was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE /reactions/1
  def destroy
    @reaction.destroy
    redirect_to reactions_url, notice: "Reaction was successfully destroyed."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reaction
      @reaction = Reaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def reaction_params
      params.require(:reaction).permit(:content)
    end
end

app/helpers/reactions_helper.rb
module ReactionsHelper
end

app/views/reactions/_reaction.html.erb
<div id="<%= dom_id reaction %>">
  <%= reaction.content %>
</div>

app/views/reactions/_reaction_form.html.erb
<div data-controller="emoji-picker" class="popper-wrapper" data-emoji-picker-show-value="false">
  <button data-emoji-picker-target="button" data-action="click->emoji-picker#toggle">
    <%= heroicon("emoji-happy", variant: :outline, options: { class: "mr-3 flex-shrink-0 h-5 w-5 text-gray-400 group-hover:text-gray-700" }) %>
  </button>
  <div data-emoji-picker-target="emojiRoot" data-action="click->emoji-picker#toggle" class="popper popper-dark">
    <emoji-picker></emoji-picker>
    <%= tag.div class: "arrow", data: {
          emoji_picker_target: "arrow",
          popper_arrow: true
        } %>
  </div>
  <%= form_with model: Reaction.new, url: comment_reactions_path(comment_id: comment.id), method: :post do |f| %>
    <%= f.hidden_field :content, data: { emoji_picker_target: "formInput" } %>
    <%= f.submit :content, class: "hidden", data: { emoji_picker_target: "formSubmit" } %>
  <% end %>
</div>

app/views/reactions/create.turbo_stream.erb
<%= turbo_stream.append(dom_id(@reaction.comment) + "_reactions") do %>
  <%= render @reaction %>
<% end %>