config/routes.rb
Rails.application.routes.draw do
  resources :comments, only: [:create, :update, :destroy, :edit] do
    resources :reactions, only: [:create]
  end
  resources :meetings, except: [:index] do
    post :start
  end
  resources :members do
    get :accept_membership
  end
  resource :team, except: [:index] do
    post :request_invite
  end
  devise_for :users

  resources :users, except: [:new, :create] do
    get :current
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "users#current"
end

app/models/member.rb
class Member < ApplicationRecord
  rolify
  belongs_to :user
  belongs_to :team
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: %i[ show edit update destroy accept_membership ]
  authorize_resource

  # GET /members or /members.json
  def index
    @members = Member.all
  end

  # GET /members/1 or /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = Member.new
  end

  # GET /members/1/edit
  def edit
  end

  def accept_membership
    @member.update(status: nil)
    redirect_to team_path
  end

  # POST /members or /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to member_url(@member), notice: "Member was successfully created." }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1 or /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to member_url(@member), notice: "Member was successfully updated." }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1 or /members/1.json
  def destroy
    @member.destroy

    respond_to do |format|
      format.html { redirect_to team_url, notice: "Member was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id] || params[:member_id])
  end

  # Only allow a list of trusted parameters through.
  def member_params
    params.require(:member).permit(:user_id, :team_id)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.erb
<%= form_with(model: member) do |form| %>
  <% if member.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(member.errors.count, "error") %> prohibited this member from being saved:</h2>

      <ul>
        <% member.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.text_field :user_id %>
  </div>

  <div>
    <%= form.label :team_id, style: "display: block" %>
    <%= form.text_field :team_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/members/_member.html.erb
<li class="p-4 flex justify-between">
  <div class="mx-3">
    <p class="text-sm font-medium text-gray-900">
      <%= member.user.username %>
      <% if member.status == "pending" %>
        <span class="font-bold text-sm m-1 p-1 bg-slate-600 text-white rounded-lg">
          pending
        </span>
      <% end %>
      <% if member.has_cached_role? :admin %>
      <span class="font-bold text-sm m-1 p-1 bg-orange-600 text-white rounded-lg">
        admin
      </span>
    <% end %>
    </p>
    <p class="text-sm text-gray-500"><%= member.user.email %></p>
  </div>
  <div>
    <% if member.status == "pending" && can?(:accept_membership, member) %>
      <%= link_to member_accept_membership_path(member) do %>
        <div class="font-bold text-sm m-1 py-1 pl-1 pr-2 bg-green-600 text-white rounded-lg">
          <%= heroicon(:check, variant: :outline, options: { class: "inline-block h-5 w-5"}) %>
          accept
        </div>
      <% end %>
    <% end %>
    <% if can?(:destroy, member) %>
      <%= button_to member_path(member), method: :delete do %>
        <div class="font-bold text-sm m-1 py-1 pl-1 pr-2 bg-red-600 text-white rounded-lg">
          <%= heroicon(:x, variant: :outline, options: { class: "inline-block h-5 w-5"}) %>
          delete
        </div>
      <% end %>
    <% end %>
  </div>
</li>

app/views/members/edit.html.erb
<h1>Editing member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Show this member", @member %> |
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/index.html.erb
<h1>Members</h1>

<div id="members">
  <% @members.each do |member| %>
    <%= render member %>
    <p>
      <%= link_to "Show this member", member %>
    </p>
  <% end %>
</div>

<%= link_to "New member", new_member_path %>

app/views/members/new.html.erb
<h1>New member</h1>

<%= render "form", member: @member %>

<br>

<div>
  <%= link_to "Back to members", members_path %>
</div>

app/views/members/show.html.erb
<%= render @member %>

<div>
  <%= link_to "Edit this member", edit_member_path(@member) %> |
  <%= link_to "Back to members", members_path %>

  <%= button_to "Destroy this member", @member, method: :delete %>
</div>